import React from "react";
import { BarChart3, CheckCircle2, ShoppingBag } from "lucide-react";
export default function AdminStatistics({ statistiques, serie=[] }) {
    const maximum=Math.max(...serie.map(point=>Math.max(point.recues||0,point.livrees||0)),1);
    return <article className="min-w-0 rounded-jse-xl border border-jse-theme-border bg-jse-theme-surface p-4 shadow-sm sm:p-6">
        <div className="flex min-w-0 flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
            <div className="min-w-0"><div className="flex min-w-0 items-center gap-2"><span className="flex size-9 shrink-0 items-center justify-center rounded-jse-moyen bg-jse-secondaire/10 text-jse-secondaire"><BarChart3 size={17}/></span><h2 className="min-w-0 break-words text-base font-semibold">Activité des commandes</h2></div><p className="mt-2 break-words text-xs leading-5 text-jse-theme-muted">Commandes reçues et livrées sur les sept derniers jours.</p></div>
            <span className="w-fit shrink-0 rounded-full border border-jse-theme-border px-3 py-1.5 text-xs font-medium text-jse-theme-muted">7 jours</span>
        </div>
        {serie.length===0 ? <div className="mt-6 flex min-h-48 items-center justify-center rounded-jse-moyen border border-dashed border-jse-theme-border px-4 text-center text-xs text-jse-theme-muted">Aucune donnée disponible pour cette période.</div> :
        <div className="mt-6 overflow-hidden"><div className="flex min-w-0 items-end gap-1.5 sm:gap-3">{serie.map(point=><div key={point.date} className="min-w-0 flex-1"><div className="flex h-32 items-end justify-center gap-0.5 sm:h-40 sm:gap-1.5"><div className="w-full max-w-3 rounded-t-jse-petit bg-jse-principal" style={{height:Math.max((point.recues/maximum)*100,point.recues?8:2)+"%"}}/><div className="w-full max-w-3 rounded-t-jse-petit bg-jse-secondaire" style={{height:Math.max((point.livrees/maximum)*100,point.livrees?8:2)+"%"}}/></div><p className="mt-2 truncate text-center text-[10px] text-jse-theme-muted sm:text-xs">{point.label}</p></div>)}</div></div>}
        <div className="mt-5 flex flex-wrap items-center gap-x-4 gap-y-2 text-xs text-jse-theme-muted"><span className="inline-flex items-center gap-2"><span className="size-2 shrink-0 rounded-full bg-jse-principal"/><ShoppingBag size={12}/>Reçues</span><span className="inline-flex items-center gap-2"><span className="size-2 shrink-0 rounded-full bg-jse-secondaire"/><CheckCircle2 size={12}/>Livrées</span></div>
        <div className="mt-6 grid grid-cols-2 gap-3"><div className="min-w-0 rounded-jse-moyen border border-jse-theme-border bg-jse-theme-surface-soft p-3"><p className="text-xs text-jse-theme-muted">Actives</p><p className="mt-1 text-lg font-semibold">{statistiques.commandes_actives??0}</p></div><div className="min-w-0 rounded-jse-moyen border border-jse-theme-border bg-jse-theme-surface-soft p-3"><p className="text-xs text-jse-theme-muted">Livrées</p><p className="mt-1 text-lg font-semibold">{statistiques.commandes_livrees??0}</p></div></div>
    </article>;
}
