import React, { useMemo, useState } from "react";
import { Head, Link, router, usePage } from "@inertiajs/react";
import { Bike, ChevronLeft, ChevronRight, Edit3, Mail, MapPin, Plus, Search, ShieldCheck, Store, UserRound, X } from "lucide-react";
import AdminSidebar from "../../Composants/Admin/AdminSidebar";

const roles = [
    { value: "client", label: "Client" },
    { value: "restaurant", label: "Restaurant" },
    { value: "livreur", label: "Livreur" },
    { value: "administrateur", label: "Administrateur" },
];
const emptyForm = { nom:"", prenom:"", telephone:"", email:"", mot_de_passe:"", role:"client", statut:"actif", restaurant_nom:"", restaurant_description:"", restaurant_telephone:"", restaurant_email:"", restaurant_adresse:"", restaurant_zone_id:"", livreur_matricule:"", livreur_zone_id:"", livreur_disponibilite:"indisponible", livreur_telephone_secondaire:"" };
const roleLabel = (role) => roles.find((r) => r.value === role)?.label || role;

export default function Utilisateurs({ utilisateurs, filtres = {}, roles: rolesDisponibles = [], administrateursActifs = 0, utilisateur, zones = [] }) {
    const { flash = {} } = usePage().props;
    const [modal, setModal] = useState(null);
    const [form, setForm] = useState(emptyForm);
    const [processing, setProcessing] = useState(false);
    const listeRoles = useMemo(() => roles.filter((r) => rolesDisponibles.includes(r.value)), [rolesDisponibles]);
    const data = utilisateurs?.data || [];

    const ouvrirCreation = () => { setForm({ ...emptyForm }); setModal({ type: "create" }); };
    const ouvrirEdition = (item) => {
        setForm({ ...emptyForm, ...item, restaurant_nom:item.restaurant?.nom || "", restaurant_telephone:item.restaurant?.telephone || "", restaurant_email:item.restaurant?.email || "", restaurant_adresse:item.restaurant?.adresse || "", livreur_matricule:item.profil_livreur?.matricule || "", livreur_zone_id:item.profil_livreur?.zone_id || "", livreur_disponibilite:item.profil_livreur?.disponibilite || "indisponible", livreur_telephone_secondaire:item.profil_livreur?.telephone_secondaire || "" });
        setModal({ type:"edit", user:item });
    };
    const changer = (champ, valeur) => setForm((etat) => ({ ...etat, [champ]: valeur }));
    const fermer = () => { if (!processing) setModal(null); };
    const soumettre = (event) => {
        event.preventDefault(); if (processing) return; setProcessing(true);
        const options = { preserveScroll:true, onFinish:()=>setProcessing(false), onSuccess:()=>setModal(null) };
        if (modal?.type === "edit") router.patch("/administration/utilisateurs/" + modal.user.id, form, options);
        else router.post("/administration/utilisateurs", form, options);
    };
    const query = (patch) => router.get("/administration/utilisateurs", { ...filtres, ...patch }, { preserveState:true, preserveScroll:true, replace:true });
    const changerStatut = (item) => {
        if (item.role === "administrateur" && item.statut === "actif" && administrateursActifs <= 1) { window.alert("Impossible de désactiver le dernier administrateur actif du système."); return; }
        router.patch("/administration/utilisateurs/" + item.id + "/statut", { statut:item.statut === "actif" ? "inactif" : "actif" }, { preserveScroll:true });
    };

    return <>
        <Head title="Utilisateurs & rôles — Administration" />
        <main className="min-h-screen overflow-x-hidden bg-jse-theme-bg text-jse-theme-text"><div className="flex min-h-screen"><AdminSidebar utilisateur={utilisateur} /><section className="min-w-0 flex-1 lg:ml-[238px]"><div className="mx-auto w-full max-w-7xl px-4 py-5 pb-28 sm:px-6 sm:py-7 lg:px-8 lg:py-9">
            <header className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[11px] font-semibold uppercase tracking-[0.16em] text-jse-secondaire">Administration</p><h1 className="mt-1.5 text-2xl font-semibold tracking-tight sm:text-4xl">Utilisateurs & rôles</h1><p className="mt-2 max-w-2xl text-xs leading-5 text-jse-theme-muted sm:text-sm">Gérez les comptes, les rôles et les accès de JSE Express.</p></div><button type="button" onClick={ouvrirCreation} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-2xl bg-jse-principal px-4 text-sm font-semibold text-white"><Plus size={17}/>Ajouter un utilisateur</button></header>
            {flash?.success && <div className="mt-5 rounded-2xl border border-jse-secondaire/20 bg-jse-secondaire/10 px-4 py-3 text-sm text-jse-principal dark:text-jse-secondaire">{flash.success}</div>}
            <section className="mt-6 rounded-[24px] border border-jse-theme-border bg-jse-theme-surface p-3 shadow-jse-carte sm:p-4"><div className="grid gap-3 lg:grid-cols-[minmax(0,1fr)_180px_180px_auto]">
                <label className="relative block"><Search size={17} className="pointer-events-none absolute left-3.5 top-1/2 -translate-y-1/2 text-jse-theme-muted"/><input value={filtres.recherche || ""} onChange={(e)=>query({ recherche:e.target.value || undefined, page:1 })} placeholder="Rechercher nom, téléphone, email, matricule..." className="h-11 w-full rounded-2xl border border-jse-theme-border bg-jse-theme-bg pl-10 pr-3 text-sm outline-none focus:border-jse-secondaire"/></label>
                <select value={filtres.role || ""} onChange={(e)=>query({ role:e.target.value || undefined, page:1 })} className="h-11 rounded-2xl border border-jse-theme-border bg-jse-theme-bg px-3 text-sm outline-none"><option value="">Tous les rôles</option>{listeRoles.map((r)=><option key={r.value} value={r.value}>{r.label}</option>)}</select>
                <select value={filtres.statut || ""} onChange={(e)=>query({ statut:e.target.value || undefined, page:1 })} className="h-11 rounded-2xl border border-jse-theme-border bg-jse-theme-bg px-3 text-sm outline-none"><option value="">Tous les statuts</option><option value="actif">Actifs</option><option value="inactif">Inactifs</option></select>
                <Link href="/administration/utilisateurs" className="inline-flex h-11 items-center justify-center rounded-2xl border border-jse-theme-border px-4 text-sm font-medium text-jse-theme-muted">Réinitialiser</Link>
            </div></section>
            <div className="mt-4 flex items-center justify-between px-1"><p className="text-xs text-jse-theme-muted">{utilisateurs?.total || 0} utilisateur(s)</p><p className="hidden text-xs text-jse-theme-muted sm:block">{administrateursActifs} administrateur(s) actif(s)</p></div>
            <section className="mt-3 hidden overflow-hidden rounded-[24px] border border-jse-theme-border bg-jse-theme-surface shadow-jse-carte md:block"><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left"><thead className="border-b border-jse-theme-border bg-jse-theme-bg/70"><tr className="text-[10px] uppercase tracking-[0.14em] text-jse-theme-muted"><th className="px-5 py-4">Utilisateur</th><th className="px-5 py-4">Contact</th><th className="px-5 py-4">Rôle</th><th className="px-5 py-4">Statut</th><th className="px-5 py-4">Créé le</th><th className="px-5 py-4 text-right">Actions</th></tr></thead>
                <tbody className="divide-y divide-jse-theme-border">{data.map((item)=><tr key={item.id} className="hover:bg-jse-theme-bg/50"><td className="px-5 py-4"><div className="flex items-center gap-3"><Avatar item={item}/><div className="min-w-0"><p className="truncate text-sm font-semibold">{[item.prenom,item.nom].filter(Boolean).join(" ") || "Sans nom"}</p>{item.restaurant?.nom && <p className="truncate text-xs text-jse-theme-muted">{item.restaurant.nom}</p>}{item.profil_livreur?.matricule && <p className="truncate text-xs text-jse-theme-muted">{item.profil_livreur.matricule}</p>}</div></div></td>
                    <td className="px-5 py-4 text-xs text-jse-theme-muted"><p>{item.telephone}</p>{item.email && <p className="mt-1">{item.email}</p>}</td><td className="px-5 py-4"><RoleBadge role={item.role}/></td><td className="px-5 py-4"><StatusBadge statut={item.statut}/></td><td className="px-5 py-4 text-xs text-jse-theme-muted">{item.created_at || "—"}</td>
                    <td className="px-5 py-4"><div className="flex justify-end gap-2"><button type="button" onClick={()=>ouvrirEdition(item)} className="inline-flex h-9 items-center gap-1.5 rounded-xl border border-jse-theme-border px-3 text-xs font-semibold"><Edit3 size={14}/>Modifier</button><button type="button" onClick={()=>changerStatut(item)} className="inline-flex h-9 items-center rounded-xl bg-jse-theme-bg px-3 text-xs font-semibold">{item.statut === "actif" ? "Désactiver" : "Activer"}</button></div></td></tr>)}</tbody></table></div>{data.length===0 && <EmptyState/>}</section>
            <section className="mt-3 space-y-3 md:hidden">{data.map((item)=><article key={item.id} className="rounded-[24px] border border-jse-theme-border bg-jse-theme-surface p-4 shadow-jse-carte"><div className="flex items-start gap-3"><Avatar item={item}/><div className="min-w-0 flex-1"><p className="truncate font-semibold">{[item.prenom,item.nom].filter(Boolean).join(" ") || "Sans nom"}</p><div className="mt-1 space-y-1 text-xs text-jse-theme-muted"><p>{item.telephone}</p>{item.email && <p className="flex items-center gap-1"><Mail size={12}/>{item.email}</p>}</div></div></div><div className="mt-4 flex flex-wrap gap-2"><RoleBadge role={item.role}/><StatusBadge statut={item.statut}/></div>{(item.restaurant?.nom || item.profil_livreur?.matricule || item.profil_livreur?.zone) && <div className="mt-4 rounded-2xl bg-jse-theme-bg p-3 text-xs text-jse-theme-muted">{item.restaurant?.nom && <p className="font-medium">{item.restaurant.nom}</p>}{item.profil_livreur?.matricule && <p>Matricule : {item.profil_livreur.matricule}</p>}{item.profil_livreur?.zone && <p className="mt-1 flex items-center gap-1"><MapPin size={12}/>{item.profil_livreur.zone}</p>}</div>}<div className="mt-4 grid grid-cols-2 gap-2"><button type="button" onClick={()=>ouvrirEdition(item)} className="min-h-10 rounded-xl border border-jse-theme-border text-xs font-semibold">Modifier</button><button type="button" onClick={()=>changerStatut(item)} className="min-h-10 rounded-xl bg-jse-theme-bg text-xs font-semibold">{item.statut === "actif" ? "Désactiver" : "Activer"}</button></div></article>)}{data.length===0 && <EmptyState/>}</section>
            {utilisateurs?.links?.length > 3 && <nav className="mt-5 flex items-center justify-center gap-1" aria-label="Pagination">{utilisateurs.links.map((link,index)=><button key={index} type="button" disabled={!link.url || link.active} onClick={()=>link.url && router.get(link.url,{}, { preserveState:true, preserveScroll:true })} className={["min-w-9 rounded-xl px-3 py-2 text-xs font-semibold",link.active?"bg-jse-principal text-white":"border border-jse-theme-border text-jse-theme-muted",!link.url?"opacity-40":""] .join(" ")}>{index===0?<ChevronLeft size={15}/>:index===utilisateurs.links.length-1?<ChevronRight size={15}/>:<span dangerouslySetInnerHTML={{__html:link.label}}/>}</button>)}</nav>}
        </div></section></div></main>
        {modal && <Modal modal={modal} form={form} changer={changer} fermer={fermer} soumettre={soumettre} processing={processing} roles={listeRoles} zones={zones}/>}
    </>;
}

function Avatar({item}) { return item.photo_profil ? <img src={item.photo_profil} alt="" className="size-10 rounded-2xl object-cover"/> : <div className="flex size-10 shrink-0 items-center justify-center rounded-2xl bg-jse-principal text-sm font-semibold text-white">{(item.prenom?.[0] || item.nom?.[0] || "U").toUpperCase()}</div>; }
function RoleBadge({role}) { return <span className="inline-flex rounded-full bg-jse-secondaire/10 px-2.5 py-1 text-[10px] font-semibold text-jse-principal dark:text-jse-secondaire">{roleLabel(role)}</span>; }
function StatusBadge({statut}) { return <span className={["inline-flex rounded-full px-2.5 py-1 text-[10px] font-semibold",statut==="actif"?"bg-jse-secondaire/10 text-jse-principal dark:text-jse-secondaire":"bg-red-500/10 text-red-600"].join(" ")}>{statut==="actif"?"Actif":"Inactif"}</span>; }
function EmptyState() { return <div className="px-5 py-12 text-center"><UserRound className="mx-auto text-jse-theme-muted" size={28}/><p className="mt-3 text-sm font-semibold">Aucun utilisateur trouvé</p><p className="mt-1 text-xs text-jse-theme-muted">Modifiez la recherche ou les filtres.</p></div>; }
function Field({label,required,children}) { return <label className="block"><span className="mb-1.5 block text-[11px] font-semibold text-jse-theme-muted">{label}{required?" *":""}</span>{children}</label>; }
function Modal({modal,form,changer,fermer,soumettre,processing,roles,zones}) {
    const metier = form.role === "restaurant" ? "restaurant" : form.role === "livreur" ? "livreur" : null;
    return <div className="fixed inset-0 z-[100] flex items-end justify-center bg-black/40 p-0 backdrop-blur-sm sm:items-center sm:p-5"><div className="max-h-[92vh] w-full overflow-y-auto rounded-t-[28px] bg-jse-theme-surface p-5 shadow-2xl sm:max-w-2xl sm:rounded-[28px] sm:p-7">
        <div className="flex items-start justify-between gap-4"><div><p className="text-[10px] font-semibold uppercase tracking-[0.16em] text-jse-secondaire">{modal.type==="edit"?"Modifier le compte":"Nouveau compte"}</p><h2 className="mt-1 text-xl font-semibold">{modal.type==="edit"?"Informations utilisateur":"Ajouter un utilisateur"}</h2></div><button type="button" onClick={fermer} className="flex size-10 items-center justify-center rounded-full border border-jse-theme-border"><X size={18}/></button></div>
        <form onSubmit={soumettre} className="mt-6 space-y-5"><div className="grid gap-3 sm:grid-cols-2">
            <Field label="Prénom"><input value={form.prenom} onChange={(e)=>changer("prenom",e.target.value)} className="h-11 w-full rounded-2xl border border-jse-theme-border bg-jse-theme-bg px-3 text-sm outline-none"/></Field>
            <Field label="Nom" required><input required value={form.nom} onChange={(e)=>changer("nom",e.target.value)} className="h-11 w-full rounded-2xl border border-jse-theme-border bg-jse-theme-bg px-3 text-sm outline-none"/></Field>
            <Field label="Téléphone" required><input required value={form.telephone} onChange={(e)=>changer("telephone",e.target.value)} className="h-11 w-full rounded-2xl border border-jse-theme-border bg-jse-theme-bg px-3 text-sm outline-none"/></Field>
            <Field label="Email"><input type="email" value={form.email || ""} onChange={(e)=>changer("email",e.target.value)} className="h-11 w-full rounded-2xl border border-jse-theme-border bg-jse-theme-bg px-3 text-sm outline-none"/></Field>
            <Field label="Rôle" required><select required value={form.role} onChange={(e)=>changer("role",e.target.value)} className="h-11 w-full rounded-2xl border border-jse-theme-border bg-jse-theme-bg px-3 text-sm outline-none">{roles.map((r)=><option key={r.value} value={r.value}>{r.label}</option>)}</select></Field>
            <Field label="Statut" required><select required value={form.statut} onChange={(e)=>changer("statut",e.target.value)} className="h-11 w-full rounded-2xl border border-jse-theme-border bg-jse-theme-bg px-3 text-sm outline-none"><option value="actif">Actif</option><option value="inactif">Inactif</option></select></Field>
            <Field label={modal.type==="edit"?"Nouveau mot de passe (optionnel)":"Mot de passe"} required={modal.type!=="edit"}><input type="password" minLength={8} required={modal.type!=="edit"} value={form.mot_de_passe} onChange={(e)=>changer("mot_de_passe",e.target.value)} className="h-11 w-full rounded-2xl border border-jse-theme-border bg-jse-theme-bg px-3 text-sm outline-none"/></Field>
        </div>
        {metier==="restaurant" && <div className="rounded-2xl border border-jse-theme-border bg-jse-theme-bg p-4"><p className="font-semibold">Profil restaurant</p><div className="mt-3 grid gap-3 sm:grid-cols-2"><Field label="Nom du restaurant" required={!modal.user?.restaurant}><input required={!modal.user?.restaurant} value={form.restaurant_nom} onChange={(e)=>changer("restaurant_nom",e.target.value)} className="h-11 w-full rounded-2xl border border-jse-theme-border bg-jse-theme-surface px-3 text-sm"/></Field><Field label="Téléphone restaurant" required={!modal.user?.restaurant}><input required={!modal.user?.restaurant} value={form.restaurant_telephone} onChange={(e)=>changer("restaurant_telephone",e.target.value)} className="h-11 w-full rounded-2xl border border-jse-theme-border bg-jse-theme-surface px-3 text-sm"/></Field><Field label="Email restaurant"><input type="email" value={form.restaurant_email} onChange={(e)=>changer("restaurant_email",e.target.value)} className="h-11 w-full rounded-2xl border border-jse-theme-border bg-jse-theme-surface px-3 text-sm"/></Field><Field label="Zone"><select value={form.restaurant_zone_id || ""} onChange={(e)=>changer("restaurant_zone_id",e.target.value)} className="h-11 w-full rounded-2xl border border-jse-theme-border bg-jse-theme-surface px-3 text-sm"><option value="">Aucune zone</option>{zones.map((z)=><option key={z.id} value={z.id}>{z.nom}</option>)}</select></Field><div className="sm:col-span-2"><Field label="Adresse" required={!modal.user?.restaurant}><input required={!modal.user?.restaurant} value={form.restaurant_adresse} onChange={(e)=>changer("restaurant_adresse",e.target.value)} className="h-11 w-full rounded-2xl border border-jse-theme-border bg-jse-theme-surface px-3 text-sm"/></Field></div></div></div>}
        {metier==="livreur" && <div className="rounded-2xl border border-jse-theme-border bg-jse-theme-bg p-4"><p className="font-semibold">Profil livreur</p><div className="mt-3 grid gap-3 sm:grid-cols-2"><Field label="Matricule" required={!modal.user?.profil_livreur}><input required={!modal.user?.profil_livreur} value={form.livreur_matricule} onChange={(e)=>changer("livreur_matricule",e.target.value)} className="h-11 w-full rounded-2xl border border-jse-theme-border bg-jse-theme-surface px-3 text-sm"/></Field><Field label="Disponibilité" required={!modal.user?.profil_livreur}><select required={!modal.user?.profil_livreur} value={form.livreur_disponibilite} onChange={(e)=>changer("livreur_disponibilite",e.target.value)} className="h-11 w-full rounded-2xl border border-jse-theme-border bg-jse-theme-surface px-3 text-sm"><option value="disponible">Disponible</option><option value="indisponible">Indisponible</option></select></Field><Field label="Zone"><select value={form.livreur_zone_id || ""} onChange={(e)=>changer("livreur_zone_id",e.target.value)} className="h-11 w-full rounded-2xl border border-jse-theme-border bg-jse-theme-surface px-3 text-sm"><option value="">Aucune zone</option>{zones.map((z)=><option key={z.id} value={z.id}>{z.nom}</option>)}</select></Field><Field label="Téléphone secondaire"><input value={form.livreur_telephone_secondaire} onChange={(e)=>changer("livreur_telephone_secondaire",e.target.value)} className="h-11 w-full rounded-2xl border border-jse-theme-border bg-jse-theme-surface px-3 text-sm"/></Field></div></div>}
        <div className="flex flex-col-reverse gap-2 sm:flex-row sm:justify-end"><button type="button" onClick={fermer} className="min-h-11 rounded-2xl border border-jse-theme-border px-5 text-sm font-semibold">Annuler</button><button type="submit" disabled={processing} className="min-h-11 rounded-2xl bg-jse-principal px-5 text-sm font-semibold text-white disabled:opacity-60">{processing?"Enregistrement...":"Enregistrer"}</button></div>
        </form></div></div>;
}